### ISSUE TITLE
Custom patched ImGui version

### ISSUE THREAD

**Issue by leavittx** [pthom/hello_imgui#100]
Hello!
I'm looking for a possibility to use a custom ImGui version with Hello ImGui.
Specifically I need this PR included: https://github.com/ocornut/imgui/pull/846
How is it possible to achieve that?
Thanks!

**Comment by leavittx** [comment]
Btw I don't need the docking feature

**Comment by pthom** [comment]
Hello,

Hello ImGui uses an unmodified version of ImGui (docking branch), and I would like this to stay like this in the official repository.

Concerning the usage inside Hello ImGui, adding this PR is actually very easy, you just have to merge @thedmd 's [docking-layout-external](https://github.com/thedmd/imgui/commits/feature/docking-layout-external/). More precisely, you can cherry-pick [this commit](https://github.com/thedmd/imgui/commit/c00ea01a44ae157b15dafabbeb874e47f3fd7dd7). The cherry-pick works flawlessly.

---
Note: I'm in the process of integrating this PR into [Dear ImGui Bundle](https://github.com/pthom/imgui_bundle). This should be ready in a week or two, but this will not touch HelloImGui
