### ISSUE TITLE
ImPlot Flags

### ISSUE THREAD

**Issue by saboTec** [pthom/hello_imgui#126]
Hello, i am experiencing a problem that i can not click or change any flag in ImPlot. I even used the real example from the "implot demo" to assure that i did not make any mistake. 
But on the demo LinePlots it is also not working.
![Bildschirmfoto 2024-11-07 um 14 08 52](https://github.com/user-attachments/assets/21502310-becf-4069-87be-456c1b3fe1da)
Thanks.

**Comment by pthom** [comment]
Hello,

I cannot reproduce your issue. See video below, where I launch demo_implot.py.

https://github.com/user-attachments/assets/0507c84f-e1b2-4585-9c2c-ca43738873fe

(It also works correctly with demo_implot.cpp)

Can you post an example of code where the issue is present?

**Comment by saboTec** [comment]
Hello and thanks for the respond.
Here is the code on the template added Demo_LinePlots:
<img width="1220" alt="ImPlot" src="https://github.com/user-attachments/assets/9d310c01-d256-41cd-98cd-44a8d07614cf">


void Demo_LinePlots(){
    static float xs1[1001],ys1[1001];
    for (int i=0;i<1001;++i){
        xs1[i] = i * 0.001;
        ys1[i] = 0.5f + 0.5f * sin(50*xs1[i]+(float)ImGui::GetTime()/10);
    }
    static double xs2[20],ys2[20];
    for (int i=0;i<20;++i){
        xs2[i] = i*1/19.0f;
        ys2[i] = xs2[i]*xs2[i];
    }
    if(ImPlot::BeginPlot("Line Plots))")){
        ImPlot::SetupAxes("x","y");
        ImPlot::PlotLine("f(x)",xs1,ys1,1001);
        ImPlot::SetNextMarkerStyle(ImPlotMarker_Circle);
        ImPlot::PlotLine("g(x)",xs2,ys2,20,ImPlotLineFlags_Segments);
        ImPlot::EndPlot();
    }
}
int main(int , char *[])
{
    auto guiFunction = []() {
        ImGui::Text("Hello, ");                    // Display a simple label
        HelloImGui::ImageFromAsset("world.jpg");   // Display a static image
        if (ImGui::Button("Bye!"))                 // Display a button
            // and immediately handle its action if it is clicked!
            HelloImGui::GetRunnerParams()->appShallExit = true;
        ImPlot::CreateContext();
        Demo_LinePlots();
        ImPlot::DestroyContext();
     };
    HelloImGui::Run(guiFunction, "Hello, globe", true);
    return 0;
}

**Comment by pthom** [comment]
You should not create an implot context at each frame

**Comment by saboTec** [comment]
Thank you very much. It is solved.
