### ISSUE TITLE
How to Hide the Terminal Window?

### ISSUE THREAD

**Issue by downloadproject** [pthom/hello_imgui#25]
How to Hide the Terminal Window?  
think you!

**Comment by pthom** [comment]
https://stackoverflow.com/questions/2753761/how-do-i-tell-cmake-not-to-create-a-console-window
https://cmake.org/cmake/help/latest/command/add_executable.html


So I would say (not tested).

1. Inside your CMakeLists:

````cmake
hello_imgui_add_app(your_app_name ...)
set_target_properties(your_app_name PROPERTIES WIN32_EXECUTABLE ON)
````

2. Change the main() cpp function signature to WinMain:

https://learn.microsoft.com/en-us/windows/win32/learnwin32/winmain--the-application-entry-point

**Comment by pthom** [comment]
The terminal window is now disabled by default under windows
