### ISSUE TITLE
'SDL_FLASH_UNTIL_FOCUSED':  undeclared identifier

### ISSUE THREAD

**Issue by Penghmed** [pthom/hello_imgui#26]
Hi,
Make compile on windos, is get this error can make help? 
\hello_imgui\internal\backend_impls\backend_window_helper\sdl_window_helper.cpp(145,36): error C2065: 'SDL_FLASH_UNTIL_FOCUSED':  undeclared identifier

Thanks you

**Comment by pthom** [comment]
SDL_FLASH_UNTIL_FOCUSED is a new addition to SDL. May be you are using an older version of SDL.
Three solution:
1. Comment out the line that uses this (it is not very important)$
2. Update your version of SDL
3. Use the easy install mode described in https://github.com/pthom/hello_imgui/tree/master/_example_integration
(this will download a correct version of sdl)
