### ISSUE TITLE
Access to imgui/misc/cpp/ extension

### ISSUE THREAD

**Issue by Guillaume227** [pthom/hello_imgui#35]
I am getting unresolved external errors for calls to ImGui methods placed in `imgui/misc/cpp/imgui_stdlib.h`.
Are these sources not compiled by default alongside other imgui code? 
Are there some specific steps to take in the CMakeLists.txt to pull them in?

**Comment by pthom** [comment]
Good remark, thanks! I just added this in fde73fd13bb7881fb1662506cdcd59175b691343
