### ISSUE TITLE
Initial Draw Sequence

### ISSUE THREAD

**Issue by Guillaume227** [pthom/hello_imgui#41]
Upon launching my the hello_imgui powered version of my app I am seeing the main window appear in two steps, which does not look great. I am trying to understand where that's coming from.
I am still on Windows.

For a split second I first see this:
![image](https://user-images.githubusercontent.com/9445488/216965364-4f7185cd-7893-45ac-852d-f7b3dc64ce52.png)

That's after the first call to ShowGui() callback.

And then it becomes:
![image](https://user-images.githubusercontent.com/9445488/216965903-bab89c3d-f1ae-4ea5-9dd6-b39f4869def3.png)

Interestingly both the position of the window on the screen and the window size change (and that can't be told from the images above).
It seems that there is a first rendering pass of just the empty main window and then it picks up the dock spaces contents and somehow relocates the window (my code is not attempting any resize/change of position).

**Comment by Guillaume227** [comment]
I am on high DPI monitor (dell XPS 15 laptop). I just unplugged the extra display I was using (which is not high DPI) and I can confirm the behavior I described also happens when I use a single (laptop) screen. I am more than happy to help/test/validate any changes you have in mind.

**Comment by pthom** [comment]
Hi,

This should be solved with  https://github.com/pthom/hello_imgui/commit/d6af807aebc3cf9d87b2a3547402647f475b1054

**Comment by Guillaume227** [comment]
The glitch is gone, that looks much nicer now. Thanks Thom for the quick turnaround (and I hope you get to do other fun stuff besides coding during your week of vacation)!

**Comment by pthom** [comment]
I’m on the slopes right now .

**Comment by Guillaume227** [comment]
I was doing some more testing of that change and noticed an undesirable side effect : the `hello_imgui` app window now forces its way to the forefront all the time (e.g. I alt-tab to some other app and the `hello_imgui` app jumps back again to the front).

I think it's down to calling `showWindow()` for every frame index >= 3. Any reason not to use an equality ?

~~if (mIdxFrame >= 3)~~
if (mIdxFrame == 3)

**Comment by pthom** [comment]
Oops you are right. This needs a quick fix. Thanks ! Le 15 févr. 2023 à 14:36, Guillaume Giraud ***@***.***> a écrit :﻿
I was doing some more testing of that change and noticed an undesirable side effect : the hello_imgui app window now forces its way to the forefront all the time (e.g. I alt-tab to some other app and the hello_imgui app jumps back again to the front).
I think it's down to calling showWindow() for every frame index >= 3. Any reason not to use an equality ?
if (mIdxFrame >= 3)
if (mIdxFrame == 3)

**Comment by Guillaume227** [comment]
Ok - I sent my simple change as a PR if that makes it easier for you: https://github.com/pthom/hello_imgui/pull/47
