### ISSUE TITLE
An api which can help us get assets folder path

### ISSUE THREAD

**Issue by haohao159-XD** [pthom/hello_imgui#56]
# An New API
## Source(In `hello_imgui_assets.cpp`)
```cpp
    std::string GetAssetFolderPath() {
        std::string a = FileUtils::GetCurrentDirectory();
#if defined(__ANDROID__)
        a+="/";
#else
        a += "\\";
#endif
        a += gAssetsSubfolderFolderName;
        return a;
    }
```
## How to use
```cpp
    ImGui::Text("%s", HelloImGui::GetAssetFolderPath().c_str());
```
## Photo
![Photo](https://github.com/pthom/hello_imgui/assets/112557849/cb40c64c-d864-4386-acbc-c745034c4fad "Hello Imgui")

**Comment by pthom** [comment]
I know, the assets API is a bit complex.
However, there are up to four possible different locations for the assets folder, as shown by computePossibleAssetsFolders(), and they are all tested in succession when trying to look for an asset:

1. `gOverrideAssetsFolder` (valid only if it was filled by manually calling SetAssetsFolder())
2. Current executable folder + "/" + `gAssetsSubfolderFolderName` (gAssetsSubfolderFolderName = "assets" by default)
3. Current working directory + "/" + `gAssetsSubfolderFolderName`
4. "/" + `gAssetsSubfolderFolderName` (emscripten only)

In practice, it will mainly vary between 3 and 4.

As such, providing GetAssetFolderPath() is not that easy.

**Comment by haohao159-XD** [comment]
Thank you, your solution is very helpful!
