### ISSUE TITLE
Imgui Ini Settings Parts

### ISSUE THREAD

**Issue by mrawlingst** [pthom/hello_imgui#61]
It appears that author forgot to either ignore or correctly format the line to not cause a crash:

hello_imgui_ini_settings.cpp: line 116
`std::string r = ";;; !!! This configuration is handled by HelloImGui and stores several Ini Files, separated by markers like this:\n           ;;;<<<INI_NAME>>>;;;\n\n";`

This line is causing the application to abort whenever it attempts to read/save.

I had to readjust the string so that each line opened/closed with ;;;<<< >>>;;; in order for the app to correctly read/save file.

**Comment by pthom** [comment]
Hi,

thanks for letting me know. I pushed a fix on the master branch. 
Please tell me if it works on your side.

**Comment by mrawlingst** [comment]
That fixed it! Thank you for the work you have done.
