### ISSUE TITLE
Ability to put user menu items between the App Menu and the View Menu

### ISSUE THREAD

**Issue by kuchi** [pthom/hello_imgui#80]
Apologies if I missed it in the documentation, I want to add a File menu to the application menus. But when I add my callback using (I am using the python bindings)

    runner_params = immapp.RunnerParams()
    runner_params.callbacks.show_menus = [my menu ui function]

the menu it is by default after the View menu. If I want to have my menu ui run before the View menu is generated is there a way to specify that (or that the auto generated View menu goes after? I didn't notice any config in the runner_params that would allow me to do this.

Thanks

**Comment by pthom** [comment]
Hello Anthony,

You are right, this was a missing part of the API. I corrected this. See b2f65467fb0ba59d1946aa904f308a60c4243012

See [usage in python](https://github.com/pthom/imgui_bundle/commit/4a115187853cff1b61a117b570fc1ba9edb348a8#diff-e20737383cdf0ebf0359de471c70408e0dd1672c09072fec7ce7a529b8421e94)
