### ISSUE TITLE
how to add a toolbar (or other fixed windows) that limits the available main docking space?

### ISSUE THREAD

**Issue by wkjarosz** [pthom/hello_imgui#88]
I've been trying to find a way to create a toolbar along the top of the screen (but under the menu bar). I've found explanations for various ways to accomplish this, including using `BeginViewportSideBar`, but I'm struggling to get this to work because HelloImGui takes over the creation of the docking spaces in e.g. `DoCreateFullScreenImGuiWindow`. I found that by manually using a `BeginMainMenuBar` and a `BeginViewportSideBar` I can get the effect I want, but the full screen docking space that HelloImGui creates only knows about its own status bar at the bottom, so the docking space is sized and position in a way where my additional menubar and tool/sidebar cover up the docking drop zones and HelloImGui's own menubar. If I edit `DoCreateFullScreenImGuiWindow`, I can make the fullscreen docking space start just below my top bars, but I'd prefer to find a solution that didn't require me to manually change/fork HelloImGui.

Do you have a suggested way to accomplish this, or is this currently outside the scope of what HelloImGui can allow? If its not possible to accomplish this right now, is there a clean way for me to create and manage my own docking spaces, menu/tool/statusbars, but still rely on HelloImGui's crossplatform backend and asset support?

(On a related note, is there a reason why you used `BeginMenuBar` and not `BeginMainMenuBar` for the top menu in docking mode?)

Thanks

**Comment by pthom** [comment]
Can you Please post a sample for repro

**Comment by pthom** [comment]
Done, see [ImGuiWindowParams](https://pthom.github.io/hello_imgui/book/doc_params.html#imguiwindowparams) doc (look for "Change the dockspace or background window size")

**Comment by wkjarosz** [comment]
Thanks. I'll give it a try! I suspect, however, that this will only allow adding a toolbar **above** the top menu bar, since `BeginMenuBar` is created within the full dock space/window. Using `BeginMainMenuBar` in that situation might be a way to solve this.

**Comment by wkjarosz** [comment]
I probably spoke too soon, I see there are mentions of `BeginMainMenuBar` in the new code. I'll try it out.

**Comment by wkjarosz** [comment]
This is fantastic! Exactly what I needed. Thank you for the rapid response.

There is one issue, which is that below my toolbar, there is a hidden and unused menubar. I believe this is because the main docking window still has the menubar flag set, which is not needed since the menubar is now provided by `BeginMainMenuBar` now. Here is a screenshot showing this when setting the windowbg color to be pretty transparent. Note that you can see the blue of the custom background through the top part of the semitransparent toolbar, but the bottom part of it is darker because there is a menu bar behind it too.

![image](https://github.com/pthom/hello_imgui/assets/10929749/70103b6f-0de1-4f24-8690-9c1e169dcbea)

**Comment by pthom** [comment]
> This is fantastic! Exactly what I needed. Thank you for the rapid response.

Thanks !

> There is one issue, which is that below my toolbar, there is a hidden and unused menubar. I believe this is because the main docking window still has the menubar flag set, which is not needed since the menubar is now provided by BeginMainMenuBar

Since you have the setup to reproduce the issue, can you try and remove 
```cpp
    if (imGuiWindowParams.showMenuBar)
        window_flags |= ImGuiWindowFlags_MenuBar;
```
inside `DoCreateFullScreenImGuiWindow`, and if it works push a PR (or inform me)

**Comment by pthom** [comment]
Your suggestion made me think that I should add a callback `ShowTopToolbar` to RunnerCallbacks

**Comment by pthom** [comment]
The issue with transparent window bg was actually complex to track: it required to call BeginMainMenuBar() when no window is created.

[This commit](https://github.com/pthom/hello_imgui/commit/4ac930c0ae7441e394d9e9665a5ddf6bf64d5950) fixes this, and also add support for Edge Toolbars: see [related doc](https://pthom.github.io/hello_imgui/book/doc_params.html#edge-toolbars-callbacks)

**Comment by wkjarosz** [comment]
I can confirm this works great. Thanks!
