### ISSUE TITLE
Linux build error when using glfw

### ISSUE THREAD

**Issue by codecat** [pthom/hello_imgui#9]
On Archlinux I am getting the following error when compiling with `HELLOIMGUI_USE_GLFW_OPENGL3`.

```c++
/usr/bin/ld: external/hello_imgui/external/libglad.a(glad.c.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
```

I can fix this by linking with `dl`, but perhaps this should be fixed in the library directly:

https://github.com/pthom/hello_imgui/blob/4ae3507a96ef5483efe76ca5579c61be215f00df/src/hello_imgui/CMakeLists.txt#L108

**Comment by pthom** [comment]
Hi, thanks for letting me know! This problem did not occur on Ubuntu; anyhow, since the fix is harmless, I fixed in 6e5e420 (for both sdl and glfw).
