### ISSUE TITLE
Is there a way to make input_text to show only the last part of the text while deactivated

### ISSUE THREAD

**Issue by juseus03** [pthom/hello_imgui#90]
Hi,

I am displaying a long path in a input_text widget, since the user should be able to edit it. As it is really long, I would like to display only the last part of the path, something like:
<img width="226" alt="path_example" src="https://github.com/pthom/hello_imgui/assets/13950270/77ded6dc-aaed-4c53-9b62-367b9b3275c2">

I've tried using the callbacks and setting the cursor position, but then, this doesn't allow any editing because the cursor is always at the end. Any idea how to do it?

**Comment by pthom** [comment]
Hello,

This is a more question related to ImGui I guess, and by [searching in the issues](https://github.com/ocornut/imgui/issues?q=is%3Aissue+is%3Aopen+inputtext+cursor+position), you can find [this](https://github.com/ocornut/imgui/issues/1972). As far as I saw, it may be not possible.

But, you would need to search for a file dialog library, such as [portable-file-dialogs](https://github.com/samhocevar/portable-file-dialogs) or [ImFileDialog](https://github.com/pthom/ImFileDialog.git) , which by the way are provided directly inside the sister library [ImGui Bundle](https://pthom.github.io/imgui_bundle/index.html)

**Comment by pthom** [comment]
> while deactivated 

You can detect its state and change the content based on "is it activated or not". This + ImGui::CalcTextSize
