### ISSUE TITLE
offline build

### ISSUE THREAD

**Issue by rexainn** [pthom/hello_imgui#91]
How can I change the CMakeLists or any other file to make sure "we don't download dlg from the github"? 

I can download the dlg on my own laptop and pass it on the server, but I can't download from "https://github.com/nyorain/dlg.git/" while building hello_imgui.

![image](https://github.com/pthom/hello_imgui/assets/111296458/2ccfe22f-088e-463f-90b8-919ea94516bb)

**Comment by pthom** [comment]
Try to run `git submodule update --init` manually instead of relying on CMake to do it for you. It seems that cmake fails on https in your case. 

Keep me informed, please

**Comment by rexainn** [comment]
The problem is that git submodule update --init not works, because my server can't access github. So I need to manually install on my laptop and pass it on the server. But I don't know where to store dlg in the hello_imgui.

**Comment by rexainn** [comment]
And dlg is the dependency of freetype, it's not in the git submodule

**Comment by pthom** [comment]
`git submodule update --init` does not work?

That is the first important issue. Can you clone a anything from github? How did you clone the repository in the first place? May be you are facing a temporary issue with github.
In the meantime `DHELLOIMGUI_USE_FREETYPE=OFF`

**Comment by pthom** [comment]
... but you will likely fail on the next dependency: glfw

**Comment by pthom** [comment]
Otherwise, for a build without connection, first install the dependencies with vcpkg (you will need to have installed freetype and glfw)

**Comment by rexainn** [comment]
nope...in china, the github need vpn to access, but my server can't set a vpn. So I download everything needed on my own laptop, and pass it on the server through sftp.

So I want to know how can I make all the dependencies from the local dir, and not download again from the github on the server.

**Comment by rexainn** [comment]
I've built freetype successfully, but when I run `pip install -v .` for imgui-bundle, it still try to download and build freetype from github.

![image](https://github.com/pthom/hello_imgui/assets/111296458/5ebcd11a-0dcc-4815-a5c8-25c476af86f7)

**Comment by pthom** [comment]
Because it needs a newer version of freetype than the one available with apt-get.

Use vcpkg, or add submodule for freetype and glfw + add_subdirectory for them before adding imgui_bundle

**Comment by rexainn** [comment]
It's the newest version from official: https://github.com/freetype/freetype, I built it from source.

I'm sorry but how can I add submodule + add_subdirectory for imgui_bundle? I think this is the point. I've built the freetype but not in a imgui_bundle known way.

**Comment by pthom** [comment]
I just understood you are trying to build a pip package, which you did not mention clearly.

There is no easy way to bypass the download for pip building now. 

My advice: build a wheel on a machine connected to the internet and use this wheel on your server.

**Comment by pthom** [comment]
I added some doc for vcpkg + offline usage:

https://github.com/pthom/imgui_bundle/blob/548e1e021b3e0c87e82c5f4dd0d9d1e73eaa4b45/CMakeLists.txt#L225-L253
