### ISSUE TITLE
Problems with implot from vcpkg

### ISSUE THREAD

**Issue by sabudilovskiy** [pthom/hello_imgui#93]
Hi, I tried to use your project together with implot, supplied from vcpkg. I came across the fact that implot pulls its imgui from vcpkg, which does not have backend files, even if you throw it into hello_imgui, it will not work, well, there is a slightly different name for the target, but this is solved by alias. I don't understand well what you can try to do in such a situation. Hypothetically, if the backends you use were in separate targets (with separate settings), then you could use the package from vcpkg, turn off the imgui build along with hello_imgui and it would work.

**Comment by pthom** [comment]
Hello,

Using imgui and/or implot from vcpkg is not recommended. HelloImGui provides its own copy of ImGui (on the docking branch).

You have two solutions:

1. Add ImPlot manually (as a submodule for example):

```cmake
add_library(implot implot/implot.cpp implot/implot.h etc...)
target_link_library(implot PUBLIC imgui)
``` 

2. If you really want to use vcpkg for implot

In this case, both ImGui and ImPlot will need to come from vcpkg.

See instructions here (following a recent commit):

https://github.com/pthom/hello_imgui/blob/94a03971392223f6c6f343b61b2434201a506009/CMakeLists.txt#L245-L290
